version: "3.7"
services: 
  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: egg
      POSTGRES_PASSWORD: password
      POSTGRES_DB: challenge
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    depends_on: 
      - postgres
    ports:
      - "8080:8080"

